parser: '@typescript-eslint/parser'
parserOptions:
  tsconfigRootDir: ./
  sourceType: module
env:
  es6: true
  node: true
extends:
  - plugin:prettier/recommended
plugins:
  - prettier
  - '@typescript-eslint'
